# --- packages/android_sender/Cargo.toml ---

[package]
name = "android_sender"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# AI-MOD-START
[dependencies]
jni = "0.21.1"
protocol = { path = "../protocol" }
# lazy_static 用于方便地创建全局可变的静态变量 (缓存)
lazy_static = "1.5.0"
# AI-MOD-END
