# --- packages/android_sender/Cargo.toml ---

[package]
name = "android_sender"
version = "0.1.0"
edition = "2021"

[lib]
# 声明这是一个动态库，供 JNI 调用
crate-type = ["cdylib"]

[dependencies]
# 我们与 Kotlin/Java 交互的唯一桥梁
jni = "0.21.1"
# AI-MOD-START
# lazy_static 已被移除，不再需要
# AI-MOD-END
