# --- packages/linux_receiver/Cargo.toml ---

[package]
name = "linux_receiver"
version = "0.1.0"
edition = "2021"

# AI-MOD-START
[dependencies]
# 引入我们自定义的传输协议 crate
protocol = { path = "../protocol" }
# 异步运行时
tokio = { version = "1", features = ["full"] }
# AI-MOD-END
